version: '3.5'

services:
  app:
    build: .
    ports:
      - '127.0.0.1:8080:8080'

  postgres:
      image: postgres:13
      ports:
        - '127.0.0.1:5432:5432'
      environment:
        POSTGRES_PASSWORD: wallet
